services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reportshub
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  reports-api:
    build: .
    container_name: reports-container
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/reportshub?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword

  reports-frontend:
    build: C:\ReportsManager\Report-Manager\reportmanager-frontend
    container_name: reports-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - reports-api

volumes:
  mysql_data: